# Generated by Django 5.1.1 on 2026-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='doc_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
